### ISSUE TITLE
horizontal navigation

### ISSUE THREAD

**Issue by nenonano** [mechevarria/patternfly-seed#2]
Hi Mike

first of all, min e is not an issue but very likely something I'm missing at all (quite a newbie here)

I tried to replace the vertical navigation with the horizontal one (no pf-X object for it) and so edited all involved files accordingly to the code I see on pf's code page.. 
as a result I have the horizontal navigation bar displayed but all the dropdown menus aren't working
I checked almost 12 times my code and compared it to the examples and I can't see any relevant (for me) difference..

any hint?

TIA
S.

**Comment by mechevarria** [comment]
Couple ways to fix, the right way and wrong way.  

The dropdowns are not working because the example code is relying on a jQuery implementation, not Angular.  The right way is to change the dropdown markup to use [UI Bootstrap Dropdown](https://angular-ui.github.io/bootstrap/#!#dropdown).  An example I have is in the navigation component html, [nav.html](https://raw.githubusercontent.com/mechevarria/patternfly-seed/master/app/components/nav/nav.html).  I also made another example in [Plunkr](https://plnkr.co/edit/X6D0cavndjK43LmUKaFY?p=preview)

The wrong way is to include bootstrap.js in your index.html after jquery.  It could be harmless, but since its not included in the Patternfly examples is could cause issues.  This is an older post since it still talks about directives, but it goes over why boostrap.js isn't good for an Angular app 

https://scotch.io/tutorials/how-to-correctly-use-bootstrapjs-and-angularjs-together

By the way, if you are learning, scotch.io has excellent tutorials

**Comment by nenonano** [comment]
thank you very much for your hints (and your blazing fast answer too), I'll take a look al all of them
ciao
